project:
  title: "MathFoundationsDS"
  output-dir: _slides
  render:
    - MathFoundationsDS.qmd
    - Lec00-VectorsMatrices1.qmd
    - Lec01-VectorsMatrices2.qmd
    - Lec02-OrthogonalityProjections.qmd
    - Lec03-QRFactorization.qmd
    - Lec04-LeastSquares.qmd
    - Lec05-LinearSystems.qmd
    - Lec06-Eigenvalues.qmd
    - Lec07-SVD.qmd
    - Lec08-Derivatives1.qmd
    - Lec09-Derivatives2.qmd
    - Lec10-Integration.qmd
    - Lec11-Optimization1.qmd
    - Lec12-Optimization2.qmd
    - Lec13-Optimization3.qmd
    - Lec14-Optimization4.qmd
    - Lec15-ProbabilityIntroduction.qmd
    - Lec16-RandomVariables.qmd
    - Lec17-Expectation.qmd
    - Lec18-InequalitiesLimitTheorems.qmd
    - Lec19-ParameterEstimationMLE.qmd
    - Lec20-BayesianStatistics1.qmd
    - Lec21-BayesianStatistics2.qmd
    - Lec22-MarkovChains.qmd
    - Lec23-HiddenMarkovModels.qmd
    - Lec24-SamplingAlgorithms.qmd
    - LecYY-MidtermReview.qmd

format:
  revealjs:
    footer: "DS722 - Ladenheim"
    scrollable: true
    slide-number: c/t
    show-slide-number: all
    chalkboard: true
    html-math-method: mathjax
    echo: true
    code-fold: true

