---
title: "DS722 — Mathematical Foundations of Data Science and Machine Learning"
author: "Scott Ladenheim"
format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
---

"A mathematician, on the other hand, has no material to work with but ideas, and so his patterns are likely to last longer, since ideas wear less with time than words." -- G.H. Hardy, _A Mathematician's Apology_

## Preface {.unnumbered}

Welcome to DS722 _Mathematical Foundations of Data Science and Machine Learning_!

These are the course lecture notes for DS722, _Mathematical Foundations of Data Science and Machine Learning_.

If you have suggestions, feel free to create a Github issue. If you find typos or
errors, please create an issue, or better yet, submit a pull request.


## Format {.unnumbered}

This course notes site is built using [Quarto](https://quarto.org/) and all the
source pages are in Quarto markdown files. Each link below opens a reveal.js deck.

## Linear Algebra

- [Math Basics](Lec01-MathBasics.html)
- [Vectors and Matrices](Lec02-VectorsMatrices.html)
- [Orthogonality and Projections](Lec03-OrthogonalityProjections.html)
- [QR Factorization](Lec04-QRFactorization.html)
- [Least Squares](Lec05-LeastSquares.html)
- [Linear Systems and LU Factorization](Lec06-LinearSystems.html)
- [Eigenvalues](Lec07-Eigenvalues.html)
- [Singular Value Decomposition](Lec08-SVD.html)

## Calculus

- [Derivatives I](Lec09-Derivatives1.html)
- [Derivatives II](Lec10-Derivatives2.html)
- [Integration](Lec11-Integration.html)

## Optimization

- [Optimization](Lec12-Optimization1.html)
- [First Order Methods](Lec13-Optimization2.html)
- [Second Order Methods](Lec14-Optimization3.html)
- [Quasi-Newton Methods](Lec15-Optimization4.html)

## Probability and Statistics

- [Introduction to Probability](Lec16-ProbabilityIntroduction.html)
- [Random Variables and Distributions](Lec17-RandomVariables.html)
- [Expectation, Variance, and Moments](Lec18-Expectation.html)
- [Inequalities and Limit Theorems](Lec19-InequalitiesLimitTheorems.html)
- [Parameter Estimation (MLE)](Lec20-ParameterEstimationMLE.html)
- [Bayesian Statistics I](Lec21-BayesianStatistics1.html)
- [Bayesian Statistics II](Lec22-BayesianStatistics2.html)

<!-- 
## Stochastic Processes

- [Markov Chains](Lec23-MarkovChains.html)

## Review

- [Midterm Review](LecYY-MidtermReview.html) -->