---
title: "0 Matrix Operations"
author: "Yuke Zhang"
---

## Little about me 
:::: {.incremental}
- Contact
    - Office: 14th floor Desk #10
    - Email: yukez@bu.edu
- Education
    - BS in Mathematics and Data Science at Purdue University
    - Current 3rd year CDS Ph.D. student at our Boston University
- Fun Facts
    - 3-semester Python programming course TA experience
    - Some LLM fine-tuning and prompt engineering experience
        - Obtained silver medals in Kaggle competions on AI Mathematical Olympiad and ARC Prize 2024
    - Research interest is statistical foundation on deep learning, specifically on spatio-temporal modeling using climate data.
- "He who refuses to do arithmetic is doomed to talk nonsense." from Computer Scientist John McCarthy

::::


## From Lecture

We introduced

:::: {.incremental}
1. Key notation and terminology for vectors and matrices
1. Vector spaces, Span, and Basis 
1. Matrix-vector and matrix-matrix products
1. How a neural network uses matrix operations for forward propagation
1. Vector and matrix norms
::::


## In this Discussion

We focused on how to 

:::: {.incremental}
1. Setup SCC notebook
2. Work out the results and runtime of matrix–vector and matrix–matrix products  
3. Compare their speed on CPU vs. GPU (Optional)
::::


## Create a session accessing Jupyter Notebook
Search SCC ondemand, login through BU account

:::: {.incremental} 
1.  Create a folder under /projectnb/ds722/student if you havent' do so
    - Click "**Files**" and select **/projectnb/ds722** and select **student** subfolder
2. Click "**Interactive apps**"
    - List of modules to load (space separated) = 
        - **miniconda** 
        - **academic-ml/fall-2025**
    - Pre-Launch Command (optional) = **conda activate fall-2025-pyt**
    - Interface = **lab**
    - Working Directory = **/projectnb/ds722/student/[username]**
    - Number of hours = **2**
    - Number of cores = **1**
    - Number of gpus = **0**
    (In order to use gpu, we need that for last question, just specify Number of gpus = **1** in another session)
    - Projects = **ds722**
3. Add Discussion notebook to SCC
::::


## Notation

A column vector of length $m$, $\mathbf{x}\in\mathbb{R}^{m}$, is a 1-dimensional (1-D) array of real numbers

$$
\mathbf{x} =
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_m
\end{bmatrix}.
$$

The $i$th element of the vector is denoted $x_i$.

---

A matrix with $m$ rows and $n$ columns, $A\in\mathbb{R}^{m\times n}$ is a 2-D array of numbers 
$$
\small
A = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} &a_{m2} & \cdots & a_{mn} \\
\end{bmatrix}.
$$

The element at row $i$ and column $j$ is denoted $a_{ij}$. A column vector is matrix of size $m\times 1$.

---

The transpose, $A^{T}$, of a matrix $A\in\mathbb{R}^{m\times n}$ is the $n\times m$ matrix

$$
\small
A^{T} =
\begin{bmatrix}
a_{11} & a_{21} & \cdots & a_{m1} \\
a_{12} & a_{22} & \cdots & a_{m2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1n} &a_{2n} & \cdots & a_{nm} \\
\end{bmatrix}.
$$

The transpose of a column vector $\mathbf{x}$ is a row vector. A row vector is a matrix of size $1\times m$.

---

A matrix is square when $m=n$. 

A square matrix is symmetric if $A=A^{T}$.

## Inner Products between vectors

The inner product of two columns vectors $\mathbf{x}, \mathbf{y}\in\mathbb{R}^n$ is the product of the transpose of $\mathbf{x}$ by $\mathbf{y}$

$$
\mathbf{x}^{T}\mathbf{y} = \sum_{i=1}^{n}x_iy_i.
$$

The notation $(\mathbf{x}, \mathbf{y}) = \mathbf{x}^{T}\mathbf{y}$ is also used to denote the inner product.

## Inner product

Given two vectors $x,y\in\mathbb{R}^{n}$ what is the flop count of the inner product?

::: {.fragment}
**Answer:** There are $n$ multiplications and $n-1$ additions for a total of $2n-1$ flops.
:::

---

```{python}
```


## A Matrix Times a Vector

Let $\mathbf{x}\in\mathbb{R}^{n}$ and let $A\in\mathbb{R}^{m\times n}$, then the matrix-vector product $\mathbf{b}=A\mathbf{x}\in\mathbb{R}^{m}$ is defined as

$$
b_{i} = \sum_{j=1}^{n}a_{ij}x_j, \quad i=1,\ldots,m.
$$


Let $a_j\in\mathbb{R}^{m}$ denote the $j$th column of $A$, then

$$
b = \sum_{j=1}^{n}x_j a_j.
$$

## Matrix-vector product

Given a matrix $A\in\mathbb{R}^{m\times n}$ and vector $x\in\mathbb{R}^{n}$ what is the flop count for the product $y=Ax$?

::: {.fragment}
**Answer:** There are $m$ inner products that each cost $2n-1$ flops for a total of $m*(2n - 1)$. 
::: 

---

```{python}
```

## A Matrix Times a Matrix

Let $A\in\mathbb{R}^{m \times n}$, $B\in\mathbb{R}^{n \times p}$, then the matrix-matrix product $C = AB \in\mathbb{R}^{m \times p}$ is defined as

$$
c_{ij} = \sum_{k=1}^{n} a_{ik}b_{kj}.
$$


## Matrix-Matrix product

Given a matrix $A\in\mathbb{R}^{m\times n}$ and matrix $B\in\mathbb{R}^{n\times p}$ what is the flop count for the product $C=AB$?

::: {.fragment}
**Answer:** There are $m\times p$ inner products costing $2n-1$ flops for a total of $mp(2n-1)$ flops.
:::

---

```{python}
```


## Column Partition

Let $X_{i,*}$ denotes $i$ th row of $X$; and $X_{*,j}$ denotes $j$ th column of $X$ 

Each column of $C$ is linear combination of columns of A with rows of B 

$$
C_{*,k} = \sum_{j=1}^{n} A_{*,j}\cdot B_{j,k}
$$



```{python}
```

## Outer Products

The outer product is a matrix-matrix product between an $m$-dimensional column vector $\mathbf{u}$ with an $n$-dimensional row vector $\mathbf{v}$, the result is an $m\times n$ (rank 1) matrix

$$
\begin{bmatrix}
u_1 \\
u_2 \\
\vdots \\
u_m
\end{bmatrix}
\begin{bmatrix}
v_1 & v_2 & \cdots & v_n
\end{bmatrix}
=
\begin{bmatrix}
v_1u_1 & \cdots & v_nu_1 \\
v_1u_2 & & v_nu_2 \\
\vdots & & \vdots \\
v_1u_m & \cdots & v_nu_m \\
\end{bmatrix}
$$

---
**Remark**: Why rank = 1 ?

Recall that rank = dim(ColSpace) = dim(RowSpace),
$$
uv = [v_1u, ..., v_nu]
$$

---
```{python}
```

